"""create messages table

Revision ID: 92a254ccd939
Revises: fda16356aa3c
Create Date: 2025-06-23 11:31:46.352417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92a254ccd939'
down_revision = 'fda16356aa3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
