"""create messages table

Revision ID: fda16356aa3c
Revises: aef3530fe364
Create Date: 2025-06-23 11:30:24.835348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fda16356aa3c'
down_revision = 'aef3530fe364'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
